version: "3.3"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=frontend"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=felipe.alarcon.rozo@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    labels:
      - "traefik.enable=true"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:(.+)}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"

      - "traefik.http.routers.api.rule=Host(`monitor.m1.vms.re`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api@internal"

      - "traefik.http.routers.api.tls.certresolver=myresolver"
    networks:
      - dev
  linker:
    image: "blackingt73/link-saver:v1.0"
    container_name: "linker"
    networks:
      - dev
    labels:
      - "traefik.http.services.linker-service.loadbalancer.server.port=80"
      - "traefik.http.routers.linker.service=linker-service@docker"
      - "traefik.http.routers.linker.entrypoints=websecure"
      - "traefik.http.routers.linker.tls.certresolver=myresolver"
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.linker.rule=Host(`m1.vms.re`)"
networks:
  dev:
volumes:
  traefik-certificates:
