version: '3'

networks:
  frontend:
    name: frontend
    external: true

services:
  linker:
    # The official v2 Traefik docker image
    build: .

    networks: ['frontend']

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.linker-service.loadbalancer.server.port=80'

      - 'traefik.http.routers.linker.service=linker-service@docker'
      - 'traefik.http.routers.linker.rule=Host(`m1.vms.re`)'
      - 'traefik.http.routers.linker.entrypoints=websecure'
      - 'traefik.http.routers.linker.tls.certresolver=myresolver'
